apiVersion: v1
kind: Service
metadata:
  name: alpha-service-dev
  namespace: dev
  labels:
    app: alpha
    env: dev
spec:
  ports:
  - port: 8011
    protocol: TCP
    targetPort: 8011
    name: http
  selector:
    app: alpha
    env: dev
