apiVersion: v1
kind: Service
metadata:
  name: base-service-dev
  namespace: dev
  labels:
    app: base
    env: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: base
    env: dev
