apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-dev
  namespace: dev
  labels:
    name: www
    env: dev
spec:
  storageClassName: manual
  nfs:
    path: /data/www_dev
    server: 192.168.1.20
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 2Gi
